---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-config
  annotations:
    {{- include "tailscale-relay.annotations" . | indent 4 }}
  labels:
    {{- include "tailscale-relay.labels" . | indent 4 }}
type: Opaque
stringData:
  TAILSCALE_AUTH_KEY: {{ .Values.config.authKey }}
