{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "exporter.serviceAccountName" . }}
  annotations:
    {{- include "tailscale-relay.annotations" . | indent 4 }}
  labels:
    {{- include "tailscale-relay.labels" . | indent 4 }}
{{ end }}