{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "exporter.serviceAccountName" . }}
  labels:
    {{- include "tailscale-relay.labels" . | indent 4 }}
{{- with .Values.labels }}{{ toYaml . | nindent 4 }}{{- end }}
{{ end }}