---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- include "sanitizedConfig" . | nindent 4 }}
