apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{ with .Values.labels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
{{- with .Values.strategy }}
  strategy: {{ toYaml . | nindent 4 }}
{{- end }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
        helm.sh/from: deploy.{{ include "app.fullname" . }}
{{ with .Values.podLabels }}{{ toYaml . | indent 8 }}{{ end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{ with .Values.podAnnotations }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "exporter.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.imagePullCredentials }}
      imagePullSecrets:
        - name: {{ template "app.fullname" . }}-image-pull
      {{- else }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.containerSecurityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.command }}
          command: {{ toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.args }}
          args: {{ toYaml . | nindent 16 }}
{{- end }}
          env:
{{- with .Values.envVariables }}
          {{ toYaml . | nindent 10 }}
{{- end }}
{{- with .Values.gitlabSecret }}
          - name: GCPE_GITLAB_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ . }}
                key: gitlabToken
{{- end }}
{{- with .Values.webhookSecret}}
          - name: GCPE_WEBHOOK_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ . }}
                key: webhookToken
{{- end }}
          envFrom:
            - secretRef:
                name: {{ template "app.fullname" . }}-config
          volumeMounts:
            - name: config
              mountPath: /etc/config.yml
              subPath: config.yml
          ports:
            - name: exporter
              containerPort: 8080
              protocol: TCP
{{- with .Values.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 16 }}
{{- end }}
{{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.hostAliases }}
      hostAliases: {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.securityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
{{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "app.fullname" . }}-config
