{{- define "imagePullCredentials" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.image.pullCredentials.registry (printf "%s:%s" .Values.image.pullCredentials.username .Values.image.pullCredentials.password | b64enc) | b64enc }}
{{- end }}
{{- if .Values.image.pullCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-image-pull
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullCredentials" . }}
{{- end }}