---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-config
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- if (and .Values.config.gitlab (not .Values.gitlabSecret)) }}
  GCPE_GITLAB_TOKEN: {{ required "gitlab token must be set" .Values.config.gitlab.token }}
{{- else if (not .Values.gitlabSecret) }}
{{- fail "gitlab token must be set" }}
{{- end }}
{{- if .Values.config.redis }}
  GCPE_REDIS_URL: {{ .Values.config.redis.url }}
{{- else if .Values.redis.enabled }}
  GCPE_REDIS_URL: {{ printf "redis://%s-redis-master.%s.svc:6379" .Release.Name .Release.Namespace }}
{{- end }}
{{- if .Values.config.server }}
{{- if .Values.config.server.webhook }}
{{- if (and .Values.config.server.webhook.enabled (not .Values.webhookSecret)) }}
  GCPE_WEBHOOK_SECRET_TOKEN: {{ required "webhook secret token must be set" .Values.config.server.webhook.secret_token }}
{{- end }}
{{- end }}
{{- end }}
